baseURL = 'https://scottbrinkmeyer.me'
languageCode = 'en-us'
title = 'A new hope'
theme = "hugo-universal-theme"
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]

# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Blog"
    identifier = "menu.blog"
    url        = "/posts/"
    weight     = 2

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 3

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+1 971 713 5166"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/sbrinkmeyer"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "http://facebook.com/sbrinkmeyer/"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "Bluesky"
    url = "https://bsky.app/profile/brinkmeyer.bsky.social"
    pre = "<i class='fab fa-2x fa-bluesky'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:scott.brinkmeyer@outlook.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"


[params]
    viewMorePostLink = "/posts/"
    author = "s.brinkmeyer"
    defaultKeywords = ["s.brinkmeyer", "about", "blog"]
    mainSections = ["posts"]
    defaultDescription = "scottbrinkmeyer blog site using Hugo"
    email = "scott.brinkmeyer@outlook.com"

    # Social media
    facebook_site = "https://www.facebook.com/sbrinkmeyer"
    twitter_site = ""
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyAELDyjsYKSHCDigxr81f8S8H2fwzbNoSM"

    latitude = "30.145682635"
    longitude = "-96.070261183"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/f/manyddaq"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>Doing the best i can.</p>"
    copyright = "all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Universal"

    # logo = "img/logo.png"
    # logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Brinkmeyer</strong>
        <br>Hempstead, TX
        <br>77445
        <br>
        <strong>United States</strong>
      </p>
      """


[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on +1 971 713 5166 or scott.brinkmeyer@outlook.com.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+1 971 713 5166" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:scott.brinkmeyer@outlook.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "trying the thing"
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"